// Generated by CoffeeScript 1.6.3
(function() {
  Kaya.App = (function() {
    function App() {}

    App.prototype.start = function() {
      return console.log("App starts.");
    };

    return App;

  })();

}).call(this);
